default: &default
  adapter: postgresql
  encoding: utf8
  port: 5432
  pool: 16
  timeout: 5000
  reconnect: true
  connect_timeout: 2
  database: <%= ENV["DATABASE_SCHEMA"] %>
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: localhost

development:
  <<: *default

test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3

production:
  <<: *default